pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat 'javac -encoding UTF-8 -cp Mission/junit-platform-console-standalone-1.7.1.jar -d classes Mission/src/*.java'
            }
        }
        stage('Test') {
            steps {
                bat 'java -cp Mission/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_result.txt'
            }
        }

        stage('Performance Test') {
                steps {
                    bat 'java -cp classes;Mission/junit-platform-console-standalone-1.7.1.jar PerformanceTest > performance_results.txt'
                }
        }


    }
    post {
        always {
            archiveArtifacts 'performance_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
